/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package test

class Library {
    boolean someLibraryMethod() {
        true
    }

    boolean lucas() {
        print 123123
    }
}
